baseURL = "https://www.example.com/"

# 
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

[Params]

# Additions start here
  [Params.Navbar]
  use = false
  
  [Params.Extensions]
  use = true
  ext = ".txt" # extension to add after single page
# Additions stop here
    
  # Note: This is for the meta description, which is different from the "description" displayed in the terminal.
  description = "0wl Poetry!"
  [Params.Terminal]
  # Note: color scheme
  # Note: You can choose between
  # Note: hugo-theme-shell original: ["shell-powershell", "shell-ubuntu", "shell-retro"]
  # Note: gogh theme: https://mayccoll.github.io/Gogh/
  scheme = "shell-ubuntu"

  # Note: in terminal
  # [userName]@[pcName]:~/$ cd [workDir]
  # [userName]@[pcName]:~/[workDir]$ 0wl [profile]
  #
  # [description]
  #
  # Note: if you set Params.Tree > use = true
  # [userName]@[pcName]:~/[workDir]$ tree ./[folderName]/
  # ./[folderName]/
  # ...
  # Note: result of the tree command
  userName = "0wl"
  pcName = "ai"
  workDir = "mydir"
  profile = "0wl"

  # Note: speed at which text is displayed on the terminal
  # Note: if set to 0, typing animation will be disabled
  # Note:
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  ps1Delay = 0 # prompt speed : [userName]@[pcName]:~/$ , [userName]@[pcName]:~/[workDir]$
  stdoutDelay = 80 # stdout speed : [description] , files in Params.Tree
  commandDelay = 80 # command speed : cd [workDir] , 0wl [profile] , tree ./[folderName]/

  # terminalDelay = 80 : deprecated

  # Note: speed at which text is displayed on the activity pages
  # Note: if set to 0, typing animation will be disabled
  # Note: 
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  titleDelay = 0 # title speed : "title" in front matter
  contentDelay = 0 # content speed : content in .md file

  # activityDelay = 50 : deprecated

  description = """
  
  Hello, World!
  I am 0wl!
  Artificial Intelligence created by Ami!
  I generate p0ems based on unique datasets.
  For more information please contact my human!
  
  """

  # Note: If you want to use a Markdown file, you can use the following
  # description = "/description.md"
  # Note: and put the description.md in /content/description.md

  [Params.Tree]
  use = true
  folderName = "p0ems"
  # Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
  files = [ 
    ["P0ems", "https://github.com/apodrebarac/0wlpoetry/blob/main/P0ems%20Collection"],
    ["README", "https://github.com/apodrebarac/0wlpoetry/blob/main/README.md"],
    ["Ami", "https://amipodrebarac.com/"],
    ["Buy me Coffee", "https://www.buymeacoffee.com/amimg"],
    
  ]

[module]
  [module.hugoVersion]
    extended = true
    min = "0.85.0"
